name: ShadowTLS Plugin Release Build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
      publish:
        description: 'Publish: If want ignore'
        required: false
jobs:
  native:
    name: Native Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Status
        run: git submodule status 'plugin/shadowtls/*' > shadowtls_status
      - name: ShadowTLS Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            plugin/shadowtls/src/main/jniLibs
          key: ${{ hashFiles('.github/workflows/*', 'bin/lib/shadowtls/*', 'shadowtls_status') }}
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle.kts') }}
      - name: Install toolchain
        run: |
          rustup toolchain install nightly-2023-12-13
          rustup override set nightly-2023-12-13
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Install rust android target
        run: ./run init action rust
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Native Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./run plugin shadowtls
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    needs:
      - native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch Status
        run: git submodule status 'plugin/shadowtls/*' > shadowtls_status
      - name: ShadowTLS Cache
        uses: actions/cache@v3
        with:
          path: |
            plugin/shadowtls/src/main/jniLibs
          key: ${{ hashFiles('.github/workflows/*', 'bin/lib/shadowtls/*', 'shadowtls_status') }}
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle.kts') }}
      - name: Release Build
        env:
          SKIP_BUILD: on
          BUILD_PLUGIN: shadowtls
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/26.1.10909125" >> local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action library
          ./gradlew :plugin:shadowtls:assembleOssRelease
          APK=$(find plugin/shadowtls/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname "$APK")
          echo "APK=$APK" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: ${{ env.APK }}
      - uses: actions/upload-artifact@v3
        with:
          name: "SHA256-ARM ${{ env.SHA256_ARM }}"
          path: ${{ env.SUM_ARM }}
      - uses: actions/upload-artifact@v3
        with:
          name: "SHA256-ARM64 ${{ env.SHA256_ARM64 }}"
          path: ${{ env.SUM_ARM64 }}
      - uses: actions/upload-artifact@v3
        with:
          name: "SHA256-X64 ${{ env.SHA256_X64 }}"
          path: ${{ env.SUM_X64 }}
      - uses: actions/upload-artifact@v3
        with:
          name: "SHA256-X86 ${{ env.SHA256_X86 }}"
          path: ${{ env.SUM_X86 }}
  publish:
    name: Publish Release
    if: github.event.inputs.publish != 'y'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Donwload Artifacts
        uses: actions/download-artifact@v3
        with:
          name: APKs
          path: artifacts
      - name: Release
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.16.2/ghr_v0.16.2_linux_amd64.tar.gz
          tar -xvf ghr.tar.gz
          mv ghr*linux_amd64/ghr .
          mkdir apks
          find artifacts -name "*.apk" -exec cp {} apks \;
          find artifacts -name "*.sha256sum.txt" -exec cp {} apks \;
          ./ghr -delete -prerelease -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" apks
